import Head from 'next/head'
import { Inter } from '@next/font/google'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram, AiFillLinkedin, AiFillGithub, AiFillBehanceSquare} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../../public/dev-ed-wave.png';
import design from '../../public/design.png';
import consulting from '../../public/consulting.png';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ghulam Ammar Yanuar Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-3 font-Poppins'>
        <section className='min-h-screen'>
          <nav className='p-10 mb-12 flex justify-between'>
            <h1 className='text-2xl'>Hi Folks!</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl text-gray-700'/></li>
              <li><a className='bg-gradient-to-r from-blue-500 to-blue-600 text-white
               px-4 py-2 rounded-md ml-6' href="#">Resume</a></li>
            </ul>
          </nav>

          <div className='text-center p-10'>
            <h2 className='text-5xl text-blue-500 font-extrabold'>Ghulam Ammar Yanuar</h2>
            <h3 className='text-2xl py-4 text-gray-600'>Frontend Developer</h3>
            <p className='font-medium py-5 leading-8 text-gray-500'>Hello There, i'm Ghulam, 22 years old from indonesian, i'm college in Informatics Engineering and i'm interested about Web Developer specialist as a Frontend Developer.</p>
          </div>

          <div className='text-5xl flex justify-center gap-10 text-gray-600 -mt-5'>
            <AiFillGithub />
            <AiFillInstagram />
            <AiFillLinkedin />
            <AiFillBehanceSquare />
          </div>

          <div className="relative mx-auto mb-12 bg-gradient-to-b from-blue-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit='cover' />
          </div>
  
        </section>

        <section>
          <div className='px-10'>
            <h3 className="text-3xl py-1">Service I Offer</h3>
            <p className="font-medium py-2 leading-8 text-gray-800">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos adipisci nobis <span className='text-blue-500'>illum quod saepe</span> laboriosam inventore pariatur ab praesentium, quae ipsum totam, dicta <span className='text-blue-500'>repellendus</span> ea rem optio tempora facere nihil?
            </p>
            <div className='mt-5 p-10 text-center shadow-lg rounded-xl my-10'>
              <Image src={design} width={100} height={100} />
              <h3 className='text-xl font-medium pt-8'>Beautiful Design</h3>
              <p className='py-2'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus harum vero ipsum rerum earum sunt?</p>
              <h4 className='py-4 text-blue-500'>Design tools i use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
